from symbols import Symbol as s

morse = {
    'a': [s.DIT, s.DAH],
    'b': [s.DAH, s.DIT, s.DIT],
    'c': [s.DAH, s.DIT, s.DAH, s.DIT],
    'd': [s.DAH, s.DIT, s.DIT],
    'e': [s.DIT],
    'f': [s.DIT, s.DIT, s.DAH, s.DIT],
    'g': [s.DAH, s.DAH, s.DIT],
    'h': [s.DIT, s.DIT, s.DIT, s.DIT],
    'i': [s.DIT, s.DIT],
    'j': [s.DIT, s.DAH, s.DAH, s.DAH],
    'k': [s.DAH, s.DIT, s.DAH],
    'l': [s.DIT, s.DAH, s.DIT, s.DIT],
    'm': [s.DAH, s.DAH],
    'n': [s.DAH, s.DIT],
    'o': [s.DAH, s.DAH, s.DAH],
    'p': [s.DIT, s.DAH, s.DAH, s.DIT],
    'q': [s.DAH, s.DAH, s.DIT, s.DAH],
    'r': [s.DIT, s.DAH, s.DIT],
    's': [s.DIT, s.DIT, s.DIT],
    't': [s.DAH],
    'u': [s.DIT, s.DIT, s.DAH],
    'v': [s.DIT, s.DIT, s.DIT, s.DAH],
    'w': [s.DIT, s.DAH, s.DAH],
    'x': [s.DAH, s.DIT, s.DIT, s.DAH],
    'y': [s.DAH, s.DIT, s.DAH, s.DAH],
    'z': [s.DAH, s.DAH, s.DIT, s.DIT],
    '0': [s.DAH, s.DAH, s.DAH, s.DAH, s.DAH],
    '1': [s.DIT, s.DAH, s.DAH, s.DAH, s.DAH],
    '2': [s.DIT, s.DIT, s.DAH, s.DAH, s.DAH],
    '3': [s.DIT, s.DIT, s.DIT, s.DAH, s.DAH],
    '4': [s.DIT, s.DIT, s.DIT, s.DIT, s.DAH],
    '5': [s.DIT, s.DIT, s.DIT, s.DIT, s.DIT],
    '6': [s.DAH, s.DIT, s.DIT, s.DIT, s.DIT],
    '7': [s.DAH, s.DAH, s.DIT, s.DIT, s.DIT],
    '8': [s.DAH, s.DAH, s.DAH, s.DIT, s.DIT],
    '9': [s.DAH, s.DAH, s.DAH, s.DAH, s.DIT]
}
