from collections import OrderedDict

from telegraph.common.symbols import Symbol as s


morse = OrderedDict()
morse['A'] = [s.DIT, s.DAH]
morse['B'] = [s.DAH, s.DIT, s.DIT, s.DIT]
morse['C'] = [s.DAH, s.DIT, s.DAH, s.DIT]
morse['D'] = [s.DAH, s.DIT, s.DIT]
morse['E'] = [s.DIT]
morse['F'] = [s.DIT, s.DIT, s.DAH, s.DIT]
morse['G'] = [s.DAH, s.DAH, s.DIT]
morse['H'] = [s.DIT, s.DIT, s.DIT, s.DIT]
morse['I'] = [s.DIT, s.DIT]
morse['J'] = [s.DIT, s.DAH, s.DAH, s.DAH]
morse['K'] = [s.DAH, s.DIT, s.DAH]
morse['L'] = [s.DIT, s.DAH, s.DIT, s.DIT]
morse['M'] = [s.DAH, s.DAH]
morse['N'] = [s.DAH, s.DIT]
morse['O'] = [s.DAH, s.DAH, s.DAH]
morse['P'] = [s.DIT, s.DAH, s.DAH, s.DIT]
morse['Q'] = [s.DAH, s.DAH, s.DIT, s.DAH]
morse['R'] = [s.DIT, s.DAH, s.DIT]
morse['S'] = [s.DIT, s.DIT, s.DIT]
morse['T'] = [s.DAH]
morse['U'] = [s.DIT, s.DIT, s.DAH]
morse['V'] = [s.DIT, s.DIT, s.DIT, s.DAH]
morse['W'] = [s.DIT, s.DAH, s.DAH]
morse['X'] = [s.DAH, s.DIT, s.DIT, s.DAH]
morse['Y'] = [s.DAH, s.DIT, s.DAH, s.DAH]
morse['Z'] = [s.DAH, s.DAH, s.DIT, s.DIT]
morse['0'] = [s.DAH, s.DAH, s.DAH, s.DAH, s.DAH]
morse['1'] = [s.DIT, s.DAH, s.DAH, s.DAH, s.DAH]
morse['2'] = [s.DIT, s.DIT, s.DAH, s.DAH, s.DAH]
morse['3'] = [s.DIT, s.DIT, s.DIT, s.DAH, s.DAH]
morse['4'] = [s.DIT, s.DIT, s.DIT, s.DIT, s.DAH]
morse['5'] = [s.DIT, s.DIT, s.DIT, s.DIT, s.DIT]
morse['6'] = [s.DAH, s.DIT, s.DIT, s.DIT, s.DIT]
morse['7'] = [s.DAH, s.DAH, s.DIT, s.DIT, s.DIT]
morse['8'] = [s.DAH, s.DAH, s.DAH, s.DIT, s.DIT]
morse['9'] = [s.DAH, s.DAH, s.DAH, s.DAH, s.DIT]
